title: <p align="center"> Nicolas C. Caruso</p> # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">  
    <a href="https://www.linkedin.com/in/nicol%C3%A1s-caruso-2a3795156/">LinkedIn </a>
     | 
    <a href="https://www.researchgate.net/profile/Nicolas-Caruso-2"> ResearchGate </a>
     | 
    <a href="https://www.researchgate.net/profile/Nicolas-Caruso-2"> Resume </a>
  </p>
  <br><br>
  <p align="justify"> I am a biologist holding a PhD. in Biology and currently enrolled in a master's degree in Data Science. 
  <br><br>
  I am currently working as Data Scientist at both private and public sector. 
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
