title: <p align="center"> Nicolas C. Caruso</p> # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">  
    <a href="https://www.linkedin.com/in/nicol%C3%A1s-caruso-2a3795156/">LinkedIn </a>
     | 
    <a href="https://www.researchgate.net/profile/Nicolas-Caruso-2"> ResearchGate </a>
     | 
    <a href="https://www.researchgate.net/profile/Nicolas-Caruso-2"> Resume </a>
  </p>
  
  <p align="justify" style="line-height:1.3"> I am a biologist holding a PhD. in Biology by 
    <a href="https://www.uns.edu.ar/"> Universidad Nacional del Sur</a>
  and currently enrolled in a master's degree in Data Science at 
    <a href="https://estudios.uoc.edu/es/masters-universitarios/data-science/presentacion"> Universitat Oberta de Catalunya.</a> 
  <br><br>
  With more than 5 year of experience in data analysis I am currently working as Data Scientist at both private and public sector.
  <br><br> 
  
  My skills:
  <html>
  <head>
      <style>
          p {
              font-size: 15px;
              
          }

          .container {
              background-color: rgb(192, 192, 192);
              width: 100%;
                  border-radius: 15px;
          }

          .skill {
              background-color: rgb(116, 194, 92);
              color: white;
              padding: 0%;
              text-align: right;
              font-size: 15px;
                  border-radius: 15px;
          }

          .R {
              width: 80%;
          }

          .python {
              width: 70%;
          }

          .SQL {
              width: 60%;
          }
      </style>
  </head>
  <body>
      <p>R</p>
      <div class="container">
          <div class="skill R">80%</div>
      </div>

      <p>Python</p>
      <div class="container">
          <div class="skill python">70%</div>
      </div>

      <p>SQL</p>
      <div class="container">
          <div class="skill SQL">60%</div>
      </div>
  </body>
  </html>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
