title: <p align="center"> Nicolas C. Caruso</p> # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">  
    <a href="https://www.linkedin.com/in/nicol%C3%A1s-caruso-2a3795156/">LinkedIn </a>
     | 
    <a href="https://www.researchgate.net/profile/Nicolas-Caruso-2"> ResearchGate </a>
     | 
    <a href="https://www.researchgate.net/profile/Nicolas-Caruso-2"> Resume </a>
  </p>
  
  <p align="justify"> I am a biologist holding a PhD. in Biology by 
    <a href="https://www.uns.edu.ar/"> Universidad Nacional del Sur</a>
  and currently enrolled in a master's degree in Data Science at 
    <a href="https://estudios.uoc.edu/es/masters-universitarios/data-science/presentacion"> Universitat Oberta de Catalunya.</a> 
  <br><br>
  With more than 5 year of experience in data analysis I am currently working as Data Scientist at both private and public sector.
  <br><br> 
  
  <div class="contentContainer">
  <div class="progressBar">
    <h4>HTML5</h4>
    <div class="progressBarContainer">
      <div class="progressBarValue value-90"></div>
    </div>
  </div>
  <div class="progressBar">
    <h4>CSS3</h4>
    <div class="progressBarContainer">
      <div class="progressBarValue value-80"></div>
    </div>
  </div>
  <div class="progressBar">
    <h4>Jquery</h4>
    <div class="progressBarContainer">
      <div class="progressBarValue value-30"></div>
    </div>
  </div>
  <div class="progressBar">
    <h4>WordPress</h4>
    <div class="progressBarContainer">
      <div class="progressBarValue value-70"></div>
    </div>
  </div>
  </div>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
